---
title: "class06 rfunction"
author: "Jacob Gil"
format: pdf
---

```{r}
# (A. Can you improve this analysis code?
# df <- data.frame(a=1:10, b=seq(200,400,length=10),c=11:20,d=NA)

#df$a <- rescale(df$a)

# #identify repition
# x <- (x- min(x) / (max(x) - min(x))
#       
# #identify further repition
# xmin <- min(x)
# 
# #use raange function
# rng <- range(x)
# x <- (x - rng[1] / (rng[2] - rng[1])

# #put into a function
# rescale <- function(x) {
#   rng <- range(x)
#   x <- (x - rng[1]) / (rng[2] - rng[1])
# }


# simple test of function
# rescale(1:1)

# #account for na values
# rescale02 <- function(x, na.rm=T) {
#   rng <- range(x, na.rm = na.rm)
#   x <- (x - rng[1]) / (rng[2] - rng[1])
#   paste(x)
# }   

#rescale02(1:10)
#rescale02(df)
```

```{r}
# Can you improve this analysis code?
library(bio3d)

# s1 <- read.pdb("4AKE") # kinase with drug
# s2 <- read.pdb("1AKE") # kinase no drug
# s3 <- read.pdb("1E4Y") # kinase with drug


## Function

#pdb reader function that reads and plots a protein from pdb
#input the string of the protein name
#output, a plot of residue vs bfactor for protein chainA
reader <- function(x){
  s <- read.pdb(x)
  s.chainA <- trim.pdb(s, chain="A", elety="CA")
  s.b <- s.chainA$atom$b
  plotb3(s.b, sse=s.chainA, typ="l", ylab="Bfactor")
}

reader("4AKE")
reader("1AKE")
reader("1E4Y")

```

